### ISSUE TITLE
Endpoints are not conforming with a pragmatic rest approach

### ISSUE THREAD

**Issue by fagossa** [maucasco/myFirtsSpringBootService#12]
```
POST "/balance/getMoney"
```

could be instead

```
POST "/balance/{accountNumber}/money"
```

For additional information you can read the comments on [issue3](https://github.com/maucasco/myFirtsSpringBootService/issues/3).

**Comment by maucasco** [comment]
Fixed , change the endpoint to debitMoney (best description to operation)

**Comment by fagossa** [comment]
endpoints are still wrong.

They should be _nouns_ **not** _verbs_
